config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  post '/guest', to: 'guest_sessions#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
  resources :comments, only: [:create, :destroy]
  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :feels, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :comment, presence: true
end

app/models/feel.rb
class Feel < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :post_tag_rels, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user, dependent: :destroy
  has_many :feels, dependent: :destroy
  has_many :felt_users, through: :feels, source: :user, dependent: :destroy
  has_many :tags, through: :post_tag_rels
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :title, presence: true, length: { maximum: 50}
  validates :content, presence: true
end

app/models/post_tag_rel.rb
class PostTagRel < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tag_rels, dependent: :destroy
  has_many :posts, through: :post_tag_rels

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts , dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  has_many :feels, dependent: :destroy
  has_many :felt_posts, through: :feels, source: :post
  has_secure_password
  validates :name, presence: true, length: { maximum: 20 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },format: { with: VALID_EMAIL_REGEX },
  uniqueness: {case_sensitive: true}
  validates :gender, presence: true
  validates :age, presence: true, numericality: {only_integer: true}
  validates :job, presence: true
  validates :area, presence: true
  has_secure_password
  validates :password, presence: true, length: {minimum: 6}, allow_nil: true
  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end
  def already_felt?(post)
    self.feels.exists?(post_id: post.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :current_user

  private

  def current_user
    return unless session[:user_id]
    @current_user = User.find_by(id: session[:user_id])
  end

  def authenticate_user
    if @current_user == nil
      flash[:notice] = "ログインが必要です"
      redirect_to("/login")
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.new(comment_params)
    if comment.save
      flash[:success] = "コメントしました"
      redirect_to comment.post
    else
      flash[:danger] = "内容がないコメントは送信できません"
      redirect_back(fallback_location: post_path(id: comment.post.id))
    end
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    flash[:danger] = "コメントを削除しました"
    redirect_to comment.post
  end

  private
    def comment_params
      params.require(:comment).permit(:user_id, :post_id, :comment)
    end
end

app/controllers/feels_controller.rb
class FeelsController < ApplicationController
  def create
    @like = current_user.feels.create(post_id: params[:post_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = Feel.find_by(post_id: params[:post_id], user_id: current_user.id)
    @like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.create(post_id: params[:post_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    @like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = params[:tag_id].present? ? Tag.find(params[:tag_id]).posts : Post.all
    @posts = @posts.page(params[:page]).per(10)
  end

  def new 
    @post=Post.new(flash[:post])
  end

  def create
    @post = @current_user.posts.new(post_params)
    if @post.save
      flash[:success] = "投稿しました"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
    if @current_user.nil?
      flash.now[:danger] = "ログインして下さい"
      render 'sessions/new'
    else
      @comment = Comment.new(post_id: @post.id, user_id: @current_user.id)
      @like = Like.new
      @feel = Feel.new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:success] = "編集しました"
      redirect_to @post
    else
      render 'posts/edit'
    end
  end

  def destroy
    @post.destroy
    flash[:success] = "削除しました"
    redirect_to root_path
  end

  private
    def post_params
      params.require(:post).permit(:title, :content, tag_ids:[])
    end

    def set_post
      @post = Post.find(params[:id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_by(email: params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:success] = "ログインしました"
      redirect_to root_path
    else
      flash.now[:danger] = "情報が一致しません"
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:danger] = "ログアウトしました"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
    @user = User.new(flash[:user])
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).per(10)
  end


  def create
    @user = User.new(user_params)
    if @user.save 
      session[:user_id] = @user.id
      flash[:success] = "登録しました"
      redirect_to root_url
    else
      render 'new'
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "編集しました"
      redirect_to root_path
    else
      render'edit'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = "ユーザーを削除しました"
    redirect_to root_path
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :gender, :age, :job, :area, :intro)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/feels_helper.rb
module FeelsHelper
end

app/helpers/guest_sessions_helper.rb
module GuestSessionsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="p-comment__item">
  <p><%= simple_format(comment.comment) %></p>
  <div class="p-comment__bottomLine">
    <span><%= link_to comment.user.name, user_path(id: comment.user_id)%></span>
    <span><%= link_to '削除', comment, method: :delete, data: { confirm: 'コメントを削除してよろしいですか？' } %></span>
    <span><%= comment.created_at.to_s(:datetime_jp) %></span>
  </div>
</div>

app/views/comments/_form.html.erb
<div class="p-comment__formBox">
  <p class="p-comment__formTitle">コメント記入</p>
  <%= form_with(model: comment, local: true) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <%= f.hidden_field :post_id %>
    <%= f.hidden_field :user_id %>
    <div class="form-group >
      <%= f.label :comment, 'コメント' %>
      <%= f.text_area :comment, class: 'form-control', rows: 10 %>
    </div>
    <%= f.submit '送信', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/posts/_editform.html.erb
<%= form_with(model: @post, local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="form-group">
    <h2><%= f.label :title, 'タイトル' %></h2>
    <%= f.text_field :title, class: 'form-control', placeholder:"質問内容をわかりやすくまとめてください" %>
  </div>
  <div class="form-group">
    <h2><%= f.label :body, '本文' %></h2>
    <p class="help-block">簡潔な言葉で質問の目的と背景をきちんと説明しましょう！</p>
    <%= f.text_area :content, class: 'form-control', rows: 10, value: @post.content %> 
  </div>
  <div class="form-group">
    <span>タグ</span>
    <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
      <div class="form-check">
        <%= tag.label class: 'form-check-label' do %>
          <%= tag.check_box class: 'form-check-input' %>
          <%= tag.text %>
        <% end %>
      </div>
    <% end %>
  </div>
  <%= f.submit '保存', class: 'btn btn-primary' %>
<% end %>

app/views/posts/_form.html.erb
<%= form_with(model: @post, local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="form-group">
    <h2><%= f.label :title, 'タイトル' %></h2>
    <%= f.text_field :title, class: 'form-control', placeholder:"質問内容をわかりやすくまとめてください" %>
  </div>
  <div class="form-group">
    <h2><%= f.label :body, '本文' %></h2>
    <p class="help-block">簡潔な言葉で質問の目的と背景をきちんと説明しましょう！（※自分である程度調べてから質問してください！）</p>
    <%= f.text_area :content, class: 'form-control', rows: 10, value:
    "#悩んでいること#


#背景・経緯・試したこと・調べたこと#


#答えて欲しいこと#" %>
  </div>
  <div class="form-group">
    <span>タグ</span>
    <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
      <div class="form-check">
        <%= tag.label class: 'form-check-label' do %>
          <%= tag.check_box class: 'form-check-input' %>
          <%= tag.text %>
        <% end %>
      </div>
    <% end %>
  </div>
  <%= f.submit '保存', class: 'btn btn-primary' %>
<% end %>

app/views/posts/edit.html.erb
<div class="d-flex align-items-center">
  <h1>編集</h1>
  <div class="ml-auto posts__linkBox">
    <%= link_to '投稿一覧', root_path, class: 'btn btn-outline-dark' %>
  </div>
</div>  
<%= render 'editform' %>

app/views/posts/index.html.erb
<div class="container">
  <table class="table table-striped">
    <tr><th>
    <h2>質問一覧</h2>
    <%= form_with url: posts_path, method: :get, class: 'posts__searchForm' do %>
      <%= select_tag :tag_id, options_from_collection_for_select(Tag.all, :id, :name, params[:tag_id]),
        {
          prompt: 'タグで絞り込み',
          class: 'form-control posts__select',
          onchange: 'submit(this.form);'
        }
      %>
    <% end %>
    </th></tr>
    <% @posts.each do |post| %>
      <tr class ="textarea">
      <td class="textarea text-dark"><h5><%= link_to post.title, post,:style => "color: black;" %></h5><br>
      <i class="fa fa-heart like-btn"></i>(<%= post.liked_users.count %>)
      <i class="fa fa-thumbs-up good"></i>(<%= post.felt_users.count %>)　　　
      <%= post.updated_at.to_s(:datetime_jp) %>　　　
      <%= link_to post.user.name ,user_path(post.user.id), :style => "color: black;" %>
      | <%= post.user.age%>歳 | <%= post.user.gender%> | <%= post.user.job%>
      </td>
      </tr>
      <% end %>
  </table>
</div>

<%= paginate @posts %>

app/views/posts/new.html.erb
<div class="d-flex align-items-center">
  <h1>質問作成</h1>
  <div class="ml-auto posts__linkBox">
    <%= link_to '投稿一覧', root_path, class: 'btn btn-outline-dark' %>
  </div>
</div>
<%= render 'form' %>

app/views/posts/show.html.erb
<div class="d-flex align-items-center mt-4 mb-4">
  <div class="ml-auto posts__linkBox">
    <% if @current_user == @post.user %>
      <%= link_to '編集', edit_post_path(@post), class: 'btn btn-outline-dark' %>
      <%= link_to '削除', @post, class: 'btn btn-outline-dark', method: :delete, data: { confirm: '削除してよろしいですか？' }  %>
    <% end %>
  </div>
</div>


<div class = "card">
  <div class = "card-header">
    <h4><%= @post.title %></h4>
    <% @post.tags.each do |tag| %>
      <span class="badge badge-primary"><%= tag.name %></span>
    <% end %>
  </div>
  <div class = "card-body" %>
    <p class = "card-text"><%= simple_format(@post.content) %></p>
    <p class = " font-weight-bold mr-10"><%= link_to @post.user.name ,user_path(@post.user.id), :style => "color: black;" %></p>
    <% if @current_user.already_liked?(@post) %>
      <%= link_to post_like_path(@post), method: :delete do %>
        <i class="fa fa-heart like-btn" ></i>
      <% end %>
    <% else %>
      <%= link_to post_likes_path(@post), method: :post do %>
        <i class="fa fa-heart unlike-btn"></i>
      <% end %>
    <% end %>
    <%=@post.likes.count%>
    <% if @current_user.already_felt?(@post) %>
      <%= link_to post_feel_path(@post), method: :delete do %>
        <i class="fa fa-thumbs-up good"></i>
      <% end %>
    <% else %>
      <%= link_to post_feels_path(@post), method: :post do %>
        <i class="fa fa-thumbs-up bad"></i>
      <% end %>
    <% end %>
    <%=@post.feels.count%>
  </div>
  
</div>
<%= render partial: 'comments/form', locals: { comment: @comment } %>
<div class="p-comment__list">
  <div class="p-comment__listTitle">コメント</div>
  <%= render @post.comments %>
</div>

app/views/users/_login_form.html.erb
<h1>ログイン</h1>
<%= form_with (scope: :session, url: login_path, local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="form-group">
    <%= f.label :name, 'ユーザー名' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password, 'パスワード' %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>
  <%= f.submit 'ログイン', class: 'btn btn-primary' %>

<% end %>

app/views/users/edit.html.erb
<h1>ユーザー情報の編集</h1>
<%= form_with(model: @user, local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
    <div class="form-group">
      <%= f.label :name, "ユーザー名" %>
      <%= f.text_field :name, class: "form-control",:placeholder => "ユーザー名"%>
    </div>
    <div class="form-group">
      <%= f.label :email, "メールアドレス" %>
      <%= f.email_field :email, class: "form-control",:placeholder => "user@example.com"%>
    </div>
    <div class="form-group">
      <%= f.label :gender,"性別" %>
      <%= f.select :gender, ['男性','女性','どちらでもない'] , {selected: '男性' },  {class: 'form-control'} %>
    </div>
    <div class="form-group">
      <%= f.label :age ,"年齢"%>
      <%= f.text_field :age, class: "form-control" ,:placeholder => 25 %>
    </div>
    <div class="form-group">
      <%= f.label :job,"職業" %>
      <%= f.text_field :job, class: "form-control",:placeholder => "例）大学４年生" %>
    </div>
    <div class="form-group">
      <%= f.label :area,"勤務地域" %>
      <%= f.text_field :area, class: "form-control",:placeholder => "例）東京都" %>
    </div>
    
    <div class="form-group">
      <%= f.label :intro, "自己紹介文" %>
      <%= f.text_area :intro, class: "form-control",:placeholder => "例）夢に向かって頑張りたいです" %>
      <p class="help-block">登録後の設定も可能です。</p>
    </div>

  <%= f.submit '作成', class: 'btn btn-primary' %>
<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>ユーザー登録</h1>
<%= form_with(model: @user, local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
    <div class="form-group">
      <%= f.label :name, "ユーザー名" %>
      <%= f.text_field :name, class: "form-control",:placeholder => "ユーザー名"%>
    </div>
    <div class="form-group">
      <%= f.label :email, "メールアドレス" %>
      <%= f.email_field :email, class: "form-control",:placeholder => "user@example.com"%>
    </div>
    <div class="form-group">
      <%= f.label :password, "パスワード" %>
      <%= f.password_field :password, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :password_confirmation, "確認用パスワード" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>
    
    <div class="form-group">
      <%= f.label :gender,"性別" %>
      <%= f.select :gender, ['男性','女性','どちらでもない'] , {selected: '男性' },  {class: 'form-control'} %>
    </div>
    <div class="form-group">
      <%= f.label :age ,"年齢"%>
      <%= f.text_field :age, class: "form-control" ,:placeholder => 25 %>
    </div>
    <div class="form-group">
      <%= f.label :job,"職業" %>
      <%= f.text_field :job, class: "form-control",:placeholder => "例）大学４年生" %>
    </div>
    <div class="form-group">
      <%= f.label :area,"勤務地域" %>
      <%= f.text_field :area, class: "form-control",:placeholder => "例）東京都" %>
    </div>
    
    <div class="form-group">
      <%= f.label :intro, "自己紹介文" %>
      <%= f.text_area :intro, class: "form-control",:placeholder => "例）夢に向かって頑張りたいです" %>
      <p class="help-block">登録後の設定も可能です。</p>
    </div>

  <%= f.submit '作成', class: 'btn btn-primary' %>
<% end %>

app/views/users/show.html.erb
<div class="card" >
  <div class="card-header">
    <div class="d-flex align-items-center">
        <% if @current_user == @user %>
          <h4>プロフィール</h4>
          　　<%= link_to "ユーザー削除", @user, method: :delete, data: { confirm: "本当に削除してもいいですか？？" }, class: 'btn btn-outline-dark' %>
          <%= link_to "編集", edit_user_path(@current_user), class: 'btn btn-outline-dark' %>
        <% end %>
    </div>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">　　名前　　:　　<%= @user.name %></li>
    <li class="list-group-item">　　性別　　:　　<%= @user.gender %></li>
    <li class="list-group-item">　　年齢　　:　　<%= @user.age %></li>
    <li class="list-group-item">　勤務地　　:　　<%= @user.area %></li>
    <li class="list-group-item">　　職業　　:　　<%= @user.job %></li>
    <li class="list-group-item">自己紹介文　:　　<%= @user.intro %></li>
  </ul>
</div>

<div class="userpost">
  <table class="table table-striped" >
    <tr><th>
    <h4>投稿</h4>
    </th></tr>
    <% if @posts.any?%>
      <% @posts.each do |post| %>
        <tr class ="textarea">
        <td class="textarea text-dark"><h5><%= link_to post.title, post,:style => "color: black;" %></h5><br>
        <i class="fa fa-heart like-btn"></i>(<%= post.liked_users.count %>)
        <i class="fa fa-thumbs-up good"></i>(<%= post.felt_users.count %>)　　　
        <%= post.updated_at.to_s(:datetime_jp) %>　　　
        <%= link_to post.user.name ,user_path(post.user.id), :style => "color: black;" %>
        | <%= post.user.age%>歳 | <%= post.user.gender%> | <%= post.user.job%>
        </td>
        </tr>
      <% end %>
    <% else %>
      <tr><th>
      <p>投稿はありません</p>
      </th></tr>
    <% end %>
  </table>
</div>