config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  post '/guest', to: 'guest_sessions#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
  resources :comments, only: [:create, :destroy]
  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :feels, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :comment, presence: true
end

app/models/feel.rb
class Feel < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :post_tag_rels, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user, dependent: :destroy
  has_many :feels, dependent: :destroy
  has_many :felt_users, through: :feels, source: :user, dependent: :destroy
  has_many :tags, through: :post_tag_rels
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :title, presence: true, length: { maximum: 50}
  validates :content, presence: true
end

app/models/post_tag_rel.rb
class PostTagRel < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tag_rels, dependent: :destroy
  has_many :posts, through: :post_tag_rels

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts , dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  has_many :feels, dependent: :destroy
  has_many :felt_posts, through: :feels, source: :post
  has_secure_password
  validates :name, presence: true, length: { maximum: 20 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },format: { with: VALID_EMAIL_REGEX },
  uniqueness: {case_sensitive: true}
  validates :gender, presence: true
  validates :age, presence: true, numericality: {only_integer: true}
  validates :job, presence: true
  validates :area, presence: true
  has_secure_password
  validates :password, presence: true, length: {minimum: 6}, allow_nil: true
  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end
  def already_felt?(post)
    self.feels.exists?(post_id: post.id)
  end
end

app/controllers/feels_controller.rb
class FeelsController < ApplicationController
  def create
    @like = current_user.feels.create(post_id: params[:post_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = Feel.find_by(post_id: params[:post_id], user_id: current_user.id)
    @like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.create(post_id: params[:post_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    @like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = params[:tag_id].present? ? Tag.find(params[:tag_id]).posts : Post.all
    @posts = @posts.page(params[:page]).per(10)
  end

  def new 
    @post=Post.new(flash[:post])
  end

  def create
    @post = @current_user.posts.new(post_params)
    if @post.save
      flash[:success] = "投稿しました"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
    if @current_user.nil?
      flash.now[:danger] = "ログインして下さい"
      render 'sessions/new'
    else
      @comment = Comment.new(post_id: @post.id, user_id: @current_user.id)
      @like = Like.new
      @feel = Feel.new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:success] = "編集しました"
      redirect_to @post
    else
      render 'posts/edit'
    end
  end

  def destroy
    @post.destroy
    flash[:success] = "削除しました"
    redirect_to root_path
  end

  private
    def post_params
      params.require(:post).permit(:title, :content, tag_ids:[])
    end

    def set_post
      @post = Post.find(params[:id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
    @user = User.new(flash[:user])
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).per(10)
  end


  def create
    @user = User.new(user_params)
    if @user.save 
      session[:user_id] = @user.id
      flash[:success] = "登録しました"
      redirect_to root_url
    else
      render 'new'
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "編集しました"
      redirect_to root_path
    else
      render'edit'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = "ユーザーを削除しました"
    redirect_to root_path
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :gender, :age, :job, :area, :intro)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/feels_helper.rb
module FeelsHelper
end

app/helpers/guest_sessions_helper.rb
module GuestSessionsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand ">
    <%= link_to "Efforts",root_path, id: "logo",class:"navbar-brand  text-white" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if @current_user %>
          <li><%= link_to 'マイページ', user_path(@current_user) ,class: 'btn btn-outline-dark'%></li>
          <li><%= link_to 'ログアウト', logout_path, method: :delete, class: 'btn btn-outline-dark' %></li>
          <li><%= link_to '質問作成', new_post_path, class: 'btn btn-outline-dark' %></li>
        <% else %>
          <%= link_to '新規登録', new_user_path, class: 'btn btn-outline-dark' %>
          <%= link_to 'ログイン', login_path, class: 'btn btn-outline-dark' %>
          <%= link_to '簡単ログイン', guest_path, method: :post, class: 'btn btn-outline-dark' %>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Effort</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>
  
  <body class="full">
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <%end%>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      正しく入力してください。
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>